### ISSUE TITLE
OAuth2 Development Workflow

### ISSUE THREAD

**Issue by aaronjae22** [dtinit/activity-pub-testbed#119]
![Image](https://github.com/user-attachments/assets/6f5fed5c-ccc3-4c66-9490-8bfe83900f30)

This issue tracks the implementation of OAuth2 authorization in our ActivityPub testbed to support account portability as described in the LOLA specification. We need to enable users to authorize one service to access their data on another service, following the standard OAuth2 authorization code flow.

This implementation will serve as a reference for developers building ActivityPub services that support account portability.

We will implement OAuth2 using django-oauth-toolkit with standard opaque tokens. This implementation will follow the sequence diagram provided before, where:

1. A user initiates a data transfer from a source service to a destination service
2. The destination service redirects the user to the source service's authorization endpoint
3. The user grants permission on the source service
4. The source service redirects back to the destination with an authorization code
5. The destination exchanges this code for an access token
6. The destination uses the token to access the user's ActivityPub data

### Related Documentation

- [RFC 6749: The OAuth 2.0 Authorization Framework](https://datatracker.ietf.org/doc/html/rfc6749)
- [LOLA Specification](https://swicg.github.io/activitypub-data-portability/)

### Scenario

Here's a detailed real-case scenario following the sequence diagram where a tester uses our testbed as a Source AP Service:

### Prerequisite: Tester Registration

```
1. Tester (Developer of Destination Service):
   - Visits testbed.example.com/register
   - Registers their service providing:
     * Service name: "MyFediverse"
     * Redirect URI: "https://myfediverse.com/oauth/callback"
     * Description: "Testing LOLA implementation"
   
2. Testbed (Our Source Service):
   - Generates and provides:
     * client_id: "mf_12345"
     * client_secret: "cs_67890xyz"
   - Stores registered redirect URI
```

### Actual Flow Following Sequence Diagram:

1. **User Initiates Transfer**
    
    ```
    # At MyFediverse (Destination Service)
    User: "I want to import my data from testbed.example.com"
    Action: Clicks "Import from Testbed" button
    
    # Destination Service prepares redirect
    URL = "https://testbed.example.com/oauth/authorize"
    Parameters:
        client_id: "mf_12345"
        redirect_uri: "https://myfediverse.com/oauth/callback"
        scope: "activitypub_account_portability"
        state: "random_secure_string_123"
    ```
    
2. **Authorization Request**
    
    ```
    # At Testbed (Our Source Service)
    1. Receives redirect
       - Validates client_id "mf_12345"
       - Checks redirect_uri matches registered
       - Verifies scope is correct
    
    2. If user not logged in:
       Shows: "Please log in to continue"
       - User enters credentials
       - Testbed validates login
    
    3. Shows authorization page:
       "MyFediverse requests access to your account data:
        - Profile information
        - Posts and activities
        - Followers and following lists
        Do you authorize this access?"
    ```
    
3. **User Grants Permission**
    
    ```
    # At Testbed's authorization page
    User: Clicks "Authorize"
    
    Testbed:
    1. Generates authorization code: "auth_code_abc123"
    2. Prepares redirect to MyFediverse:
       URL: "https://myfediverse.com/oauth/callback"
       Parameters:
           code: "auth_code_abc123"
           state: "random_secure_string_123"
    ```
    
4. **Token Exchange**
    
    ```
    # Backend request from MyFediverse to Testbed
    POST /oauth/token
    Headers:
        Content-Type: application/x-www-form-urlencoded
    Body:
        client_id: "mf_12345"
        client_secret: "cs_67890xyz"
        grant_type: "authorization_code"
        code: "auth_code_abc123"
        redirect_uri: "https://myfediverse.com/oauth/callback"
    
    # Testbed responds:
    {
        "access_token": "access_token_xyz789",
        "token_type": "Bearer",
        "expires_in": 3600,
        "scope": "activitypub_account_portability"
    }
    ```
    
5. **Data Access**
    
    ```
    # MyFediverse requests data
    GET /api/actors/123/outbox
    Headers:
        Authorization: "Bearer access_token_xyz789"
    
    # Testbed validates and responds:
    {
        "@context": "https://www.w3.org/ns/activitystreams",
        "type": "OrderedCollection",
        "totalItems": 100,
        "first": "https://testbed.example.com/api/actors/123/outbox?page=1",
        ...
    }
    ```
